### PR TITLE
Updated allowedHeadgear.hpp

### PR DESCRIPTION
**Pull request by MatsuoYutani**
Added Unsung Vietnam War Mod (Echo version)

### CODE REVIEW

**Comment by DerZade** [comment]
PRs from Huskies will be merged immediately. 

Jokes aside! Thanks a lot for the contribution. This will be included in the next update :)

**Comment by DerZade** [comment]
Hey @EckoMoire,

I just looked over your additions to the whitelist getting ready to merge and release, but it looks like you added stuff like berets. Am I correct in that assumption? 

To be clear the purpose of this whitelist is to single out the headgear which doesn't look odd when slinging it.  As [our wiki page](https://github.com/DerZade/grad_slinghelmet/wiki/Adding-a-Headgear-to-the-Whitelist) states:
> GRAD SlingHelmet implements a "Whitelist" for supported headgear. This way we can make sure the attachment of the slung helmet doesn't look odd. [...]

If you want to make further headgear slingable just because you need it in your specific case, you could still do this via the CBA settings or the provided functions instead.

**Comment by MatsuoYutani** [comment]
Well @DerZade , I did list **every** headwear in the mod, but I personally think it looks good, even with berets and straw hats, but I can make a list with only helmets if you want, no problem for me :)

**Comment by SlantX** [comment]
We would prefer a list with only helmets, that would be perfect for now. Thank you for the contribution!

**Pull request closed without merging**
